#!/usr/bin/env bash
# claudebox-server.sh — keep the Nomad control plane alive on claudebox.
#
# claudebox replaced the long-offline bigo-server as the cluster server+client. This script
# is self-healing and self-contained: it ensures the nomad binary exists, regenerates the
# server config from the live Tailscale IP, and (re)starts the agent if it is not responding.
# Runs as a NON-ROOT user process (server ports 4646-4648 are non-privileged).
#
# Install (user cron, no sudo):
#   (crontab -l 2>/dev/null; \
#    echo "@reboot $HOME/monad/scripts/claudebox-server.sh start"; \
#    echo "*/5 * * * * $HOME/monad/scripts/claudebox-server.sh keepalive") | crontab -
#
# Usage: claudebox-server.sh [start|keepalive|stop|status]
set -uo pipefail

NOMAD_VER="1.9.3"
BIN="$HOME/bin/nomad"
DATA="$HOME/nomad/data"
CFG="$HOME/nomad/server.hcl"
LOG="$HOME/nomad/nomad.log"
PIDF="$HOME/nomad/nomad.pid"
export PATH="$HOME/bin:$PATH"

ts_ip() { tailscale ip -4 2>/dev/null | head -1; }
addr()  { echo "http://$(ts_ip):4646"; }

ensure_bin() {
  [ -x "$BIN" ] && return 0
  echo "[claudebox-server] downloading nomad ${NOMAD_VER}…"
  mkdir -p "$HOME/bin"
  local tmp; tmp="$(mktemp -d)"
  curl -sSL -o "$tmp/n.zip" "https://releases.hashicorp.com/nomad/${NOMAD_VER}/nomad_${NOMAD_VER}_linux_amd64.zip" \
    && (cd "$tmp" && unzip -oq n.zip) && mv -f "$tmp/nomad" "$BIN" && chmod +x "$BIN"
  rm -rf "$tmp"
}

ensure_cfg() {
  local ip; ip="$(ts_ip)"
  [ -z "$ip" ] && { echo "[claudebox-server] no tailscale IP yet — is tailscale up?"; return 1; }
  mkdir -p "$DATA"
  cat > "$CFG" <<EOF
# Generated by claudebox-server.sh — Nomad control plane on claudebox.
data_dir   = "$DATA"
bind_addr  = "$ip"
datacenter = "dc1"
region     = "global"
advertise {
  http = "$ip:4646"
  rpc  = "$ip:4647"
  serf = "$ip:4648"
}
server {
  enabled          = true
  bootstrap_expect = 1
}
client {
  enabled = true
  meta {
    claude_account = "pro"
    role           = "server"
  }
}
plugin "raw_exec" {
  config { enabled = true }
}
log_level = "INFO"
EOF
}

running() { NOMAD_ADDR="$(addr)" "$BIN" server members >/dev/null 2>&1; }

start() {
  ensure_bin || return 1
  ensure_cfg || return 1
  if running; then echo "[claudebox-server] already up at $(addr)"; return 0; fi
  echo "[claudebox-server] starting nomad agent…"
  nohup "$BIN" agent -config="$CFG" > "$LOG" 2>&1 &
  echo $! > "$PIDF"
  for _ in $(seq 1 30); do running && break; sleep 1; done
  running && echo "[claudebox-server] up at $(addr) (pid $(cat "$PIDF"))" \
          || { echo "[claudebox-server] FAILED to come up — see $LOG"; tail -5 "$LOG"; return 1; }
}

case "${1:-keepalive}" in
  start)     start ;;
  keepalive) running || start ;;
  stop)      [ -f "$PIDF" ] && kill "$(cat "$PIDF")" 2>/dev/null && echo "stopped" || echo "not running" ;;
  status)
    if running; then
      echo "[claudebox-server] UP at $(addr)"
      NOMAD_ADDR="$(addr)" "$BIN" server members
      NOMAD_ADDR="$(addr)" "$BIN" node status
    else echo "[claudebox-server] DOWN"; fi ;;
  *) echo "usage: $0 [start|keepalive|stop|status]"; exit 2 ;;
esac
