#!/usr/bin/env bash
# claudebox-client.sh — keep claudebox joined to the monad cluster as a CLIENT.
#
# Topology decision (supersedes the earlier "migrate control plane to claudebox" attempt):
#   The cluster SERVER is V1410-1 (100.75.75.39) — it is the home-network router and is
#   online a vast majority of the time, so it makes a stable Raft leader. claudebox is
#   intermittent, so it joins as a pure client and never holds quorum. When claudebox is
#   offline the cluster keeps running on V1410-1; when it returns it re-registers and can
#   receive jobs again.
#
# Self-healing and self-contained: ensures the nomad binary (version-matched to the server),
# regenerates the client config from the live Tailscale IP, retry-joins the server, and
# (re)starts the agent if it is not responding. Runs as a NON-ROOT user process
# (client + serf ports 4646-4648 are non-privileged).
#
# Install (user cron, no sudo):
#   (crontab -l 2>/dev/null; \
#    echo "@reboot $HOME/monad/scripts/claudebox-client.sh start"; \
#    echo "*/5 * * * * $HOME/monad/scripts/claudebox-client.sh keepalive") | crontab -
#
# Usage: claudebox-client.sh [start|keepalive|stop|status]
set -uo pipefail

# Match the server's Nomad version exactly — a 1.9.x client will not register cleanly
# against a 2.0.x server. Bump this in lockstep with V1410-1's /usr/bin/nomad.
NOMAD_VER="2.0.2"

# The always-on cluster server (V1410-1 router). Override with MONAD_SERVER_IP if it ever moves.
SERVER_IP="${MONAD_SERVER_IP:-100.75.75.39}"

BIN="$HOME/bin/nomad"
DATA="$HOME/nomad/data"
CFG="$HOME/nomad/client.hcl"
LOG="$HOME/nomad/nomad.log"
PIDF="$HOME/nomad/nomad.pid"
export PATH="$HOME/bin:$PATH"

ts_ip() { tailscale ip -4 2>/dev/null | head -1; }
addr()  { echo "http://$(ts_ip):4646"; }

ensure_bin() {
  # Re-download if missing or if the version doesn't match the server.
  if [ -x "$BIN" ] && "$BIN" version 2>/dev/null | grep -q "v${NOMAD_VER}\b"; then
    return 0
  fi
  echo "[claudebox-client] installing nomad ${NOMAD_VER}…"
  mkdir -p "$HOME/bin"
  local tmp; tmp="$(mktemp -d)"
  curl -sSL -o "$tmp/n.zip" "https://releases.hashicorp.com/nomad/${NOMAD_VER}/nomad_${NOMAD_VER}_linux_amd64.zip" \
    && (cd "$tmp" && unzip -oq n.zip) && mv -f "$tmp/nomad" "$BIN" && chmod +x "$BIN"
  rm -rf "$tmp"
  [ -x "$BIN" ]
}

ensure_cfg() {
  local ip; ip="$(ts_ip)"
  [ -z "$ip" ] && { echo "[claudebox-client] no tailscale IP yet — is tailscale up?"; return 1; }
  mkdir -p "$DATA"
  cat > "$CFG" <<EOF
# Generated by claudebox-client.sh — claudebox as a CLIENT of the monad cluster.
data_dir   = "$DATA"
bind_addr  = "$ip"
datacenter = "dc1"
region     = "global"
name       = "claudebox"

advertise {
  http = "$ip:4646"
  rpc  = "$ip:4647"
  serf = "$ip:4648"
}

# No server block — claudebox never runs the control plane.
client {
  enabled = true

  # Join the always-on server (V1410-1). retry_join keeps trying if the server is
  # briefly unreachable, and re-joins automatically after either box reboots.
  server_join {
    retry_join = ["${SERVER_IP}:4647"]
    retry_max  = 0
    retry_interval = "15s"
  }

  meta {
    role           = "client"
    has_claude     = "true"
    claude_account = "pro"
    location       = "claudebox"
  }
}

plugin "docker" {
  config {
    allow_privileged = false
    volumes { enabled = true }
  }
}

plugin "raw_exec" {
  config { enabled = true }
}

telemetry {
  disable_hostname           = true
  prometheus_metrics         = true
  publish_allocation_metrics = true
  publish_node_metrics       = true
}

log_level = "INFO"
EOF
}

# A client is "up" when its local agent answers and reports itself joined to a server.
running() {
  local ip; ip="$(ts_ip)"
  [ -z "$ip" ] && return 1
  curl -fsS "http://$ip:4646/v1/agent/health" >/dev/null 2>&1
}

start() {
  ensure_bin || { echo "[claudebox-client] could not install nomad ${NOMAD_VER}"; return 1; }
  ensure_cfg || return 1
  if running; then echo "[claudebox-client] already up at $(addr)"; return 0; fi
  echo "[claudebox-client] starting nomad client agent…"
  nohup "$BIN" agent -config="$CFG" > "$LOG" 2>&1 &
  echo $! > "$PIDF"
  for _ in $(seq 1 30); do running && break; sleep 1; done
  if running; then
    echo "[claudebox-client] up at $(addr) (pid $(cat "$PIDF")), joining ${SERVER_IP}"
  else
    echo "[claudebox-client] FAILED to come up — see $LOG"; tail -5 "$LOG"; return 1
  fi
}

case "${1:-keepalive}" in
  start)     start ;;
  keepalive) running || start ;;
  stop)      [ -f "$PIDF" ] && kill "$(cat "$PIDF")" 2>/dev/null && echo "stopped" || echo "not running" ;;
  status)
    if running; then
      echo "[claudebox-client] UP at $(addr) — joined to ${SERVER_IP}"
      NOMAD_ADDR="http://${SERVER_IP}:4646" "$BIN" node status 2>/dev/null
    else echo "[claudebox-client] DOWN"; fi ;;
  *) echo "usage: $0 [start|keepalive|stop|status]"; exit 2 ;;
esac
